In [1]:
import numpy as np

In [4]:
a=np.array([2,4,6,8],dtype="int")
a

array([2, 4, 6, 8])

In [5]:
a.size

4

In [6]:
np.shape(a)

(4,)

In [9]:
b=np.array([[1,3,5],
            [2,4,6],
            [3,6,9]])
c=np.array([[[3,2,1],
             [6,5,4],
             [9,8,7]]])
print(b)
print(c)

[[1 3 5]
 [2 4 6]
 [3 6 9]]
[[[3 2 1]
  [6 5 4]
  [9 8 7]]]


In [15]:
print(np.shape(b))
print(b.size)

(3, 3)
9


In [16]:
print(np.shape(c))
print(c.size)

(1, 3, 3)
9


In [17]:
b[1:2]

array([[2, 4, 6]])

In [19]:
c[0:2:1]

array([[[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [23]:
c[0,:,0:2]

array([[3, 2],
       [6, 5],
       [9, 8]])

In [24]:
b[1,:2]

array([2, 4])

In [31]:
a1=np.array([1,2,3])
a2=np.array([[4,5],[6,7]])
a3=np.array([[[8,9],[2,3],[1,2]]])

In [33]:
a1[1]

2

In [34]:
a2[1,:]

array([6, 7])

In [35]:
a3[0,1,:]

array([2, 3])

In [39]:
sıfır=np.zeros((2,2))
sıfır

array([[0., 0.],
       [0., 0.]])

In [40]:
bir=np.ones((2,2))
bir

array([[1., 1.],
       [1., 1.]])

In [41]:
np.concatenate([sıfır,bir])

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])