In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [22]:
type(a)

numpy.ndarray

In [23]:
arr = np.array([3,15.4,8,6.7])
arr

array([ 3. , 15.4,  8. ,  6.7])

In [24]:
arr.dtype

dtype('float64')

In [25]:
arr2=np.array([3,15.4,8,6.7,2.18,5],dtype="int")
arr2

array([ 3, 15,  8,  6,  2,  5])

In [26]:
arr2.dtype

dtype('int32')

In [27]:
array = np.array([1,8.7,6.3,4],dtype="str")
array

array(['1', '8.7', '6.3', '4'], dtype='<U3')

In [28]:
np.array(36)

array(36)

In [29]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [30]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.array([[[1,2,3],[4,5,6]],
          [[9,8,7],[6,5,4]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [32]:
array1=np.array(36)
array2=np.array([1,2,3,4])
array3=np.array([[1,2,3],[4,5,6], [7,8,9]])
array4=np.array([[[1,2,3],[4,5,6]],[[9,8,7],[6,5,4]]])

print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

0
1
2
3


In [33]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [34]:
array2

array([1, 2, 3, 4])

In [17]:
array2[2]

3

In [18]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
array3[0,1]

2

In [20]:
array3[1,2]

6

In [21]:
array3[2,0]

7

In [22]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [23]:
array4[0,1,1]

5

In [24]:
array4[1,0,2]

7

In [25]:
array2

array([1, 2, 3, 4])

In [26]:
array2[2:]

array([3, 4])

In [27]:
array2[:3]

array([1, 2, 3])

In [28]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
array3[0:2,2]

array([3, 6])

In [30]:
array3[1:,0:2]

array([[4, 5],
       [7, 8]])

In [31]:
array3[:,1]

array([2, 5, 8])

In [32]:
array3[:,-1]

array([3, 6, 9])

In [34]:
array3[2,:]

array([7, 8, 9])

In [35]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [36]:
array4[0,:,1:]

array([[2, 3],
       [5, 6]])

In [38]:
array4[0,1,:]

array([4, 5, 6])

In [39]:
array4[1,1,0:2]

array([6, 5])

In [40]:
array4[1,:,0:2]

array([[9, 8],
       [6, 5]])

In [41]:
print(array2)
print(array2.size)

[1 2 3 4]
4


In [44]:
print(array3)
print(array3.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [45]:
print(array4)
print(array4.size)

[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]]
12


In [46]:
array2

array([1, 2, 3, 4])

In [47]:
np.shape(array2)

(4,)

In [48]:
np.shape(np.array([12,5,6,45,9]))

(5,)

In [49]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.shape(array3)

(3, 3)

In [51]:
new_array = np.array([[11,6,35,14,47],[7,94,72,18,49],[32,5,14,21,8]])
new_array

array([[11,  6, 35, 14, 47],
       [ 7, 94, 72, 18, 49],
       [32,  5, 14, 21,  8]])

In [52]:
np.shape(new_array)

(3, 5)

In [53]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [55]:
np.shape(array4)

(2, 2, 3)

In [56]:
new_array = np.array([[[12,54],[47,35],[11,28]],
                      [[64,99],[74,27],[86,41]],
                      [[96,53],[74,61],[58,26]]])
new_array

array([[[12, 54],
        [47, 35],
        [11, 28]],

       [[64, 99],
        [74, 27],
        [86, 41]],

       [[96, 53],
        [74, 61],
        [58, 26]]])

In [57]:
np.shape(new_array)

(3, 3, 2)

In [58]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(np.shape(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [59]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [60]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [63]:
arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [65]:
arr.reshape(2,3,-1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [66]:
arr.reshape(2,-1,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [70]:
b= np.array([[1,2,3,4],[4,5,6,7]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [71]:
np.concatenate([b,b],axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [72]:
np.concatenate([a,b])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [73]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [75]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [76]:
np.ones(5,dtype="int")

array([1, 1, 1, 1, 1])

In [77]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [78]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [79]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(0,41,8)

array([ 0,  8, 16, 24, 32, 40])

In [83]:
np.array(np.linspace(0,1,10))

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [84]:
np.random.randint(10,size=(3,5))

array([[9, 3, 0, 2, 4],
       [7, 3, 5, 3, 5],
       [6, 6, 6, 7, 9]])

In [85]:
array = np.array([12,8,5,19,5,7,13,5])
array

array([12,  8,  5, 19,  5,  7, 13,  5])

In [86]:
np.max(array)

19

In [87]:
np.min(array)

5

In [88]:
np.mean(array)

9.25

In [89]:
np.std(array)

4.710360920354193

In [16]:
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [17]:
b= np.array([2,5,6,8])
b

array([2, 5, 6, 8])

In [11]:
c= np.add(a,b)
c

array([12, 25, 36, 48])

In [12]:
d=np.multiply(a,b)
d

array([ 20, 100, 180, 320])

In [13]:
e= np.divide(a,b)
e

array([5., 4., 5., 5.])

In [14]:
f= np.dot(a,b)
f

620

In [35]:
array2

array([1, 2, 3, 4])

In [36]:
array2>6

array([False, False, False, False])

In [37]:
array2[array2>6]

array([], dtype=int32)

In [38]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
array3[array3>5]

array([6, 7, 8, 9])

In [40]:
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [41]:
array4[array4>6]

array([9, 8, 7])