In [1]:
import pandas as pd

In [2]:
seri= pd.Series([12,47,34,66,50])
seri

0    12
1    47
2    34
3    66
4    50
dtype: int64

In [3]:
type(seri)

pandas.core.series.Series

In [4]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
seri.size

5

In [6]:
seri.ndim

1

In [7]:
seri.values

array([12, 47, 34, 66, 50], dtype=int64)

In [8]:
seri.head(3)

0    12
1    47
2    34
dtype: int64

In [9]:
seri.tail(3)

2    34
3    66
4    50
dtype: int64

In [10]:
seri[0]

12

In [11]:
seri[2]

34

In [12]:
seri[3]

66

In [13]:
seri[0:2]

0    12
1    47
dtype: int64

In [14]:
seri[1:4]

1    47
2    34
3    66
dtype: int64

In [15]:
seri2= pd.Series([15,45,63,85,41],index=[1,8,5,3,6])
seri2

1    15
8    45
5    63
3    85
6    41
dtype: int64

In [16]:
seri2[1]

15

In [17]:
seri2[5]

63

In [18]:
seri3=pd.Series([15,45,63,85,41],index=["a","b","c","d","e"])
seri3

a    15
b    45
c    63
d    85
e    41
dtype: int64

In [19]:
seri3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
seri3["b"]

45

In [21]:
seri3["d"]

85

In [22]:
seri3["a":"d"]

a    15
b    45
c    63
d    85
dtype: int64

In [23]:
sozluk={"Ayşe":42,
        "Elif":26,
        "Fatma":36}
sozluk

{'Ayşe': 42, 'Elif': 26, 'Fatma': 36}

In [24]:
yeni_sozluk=pd.Series(sozluk)
yeni_sozluk

Ayşe     42
Elif     26
Fatma    36
dtype: int64

In [25]:
yeni_sozluk["Ayşe"]

42

In [26]:
import numpy as np
dizi=np.random.randint(50,size=6)
dizi

array([46,  7, 24, 11, 31, 34])

In [27]:
seri2=pd.Series(dizi)
seri2

0    46
1     7
2    24
3    11
4    31
5    34
dtype: int32

In [28]:
seri2.index=["a","b","c","d","e","f"]

In [29]:
seri2

a    46
b     7
c    24
d    11
e    31
f    34
dtype: int32

In [30]:
seri2[["b","d"]]

b     7
d    11
dtype: int32

In [31]:
seri2[["a","c","f"]]

a    46
c    24
f    34
dtype: int32

In [32]:
seri2[["b","d"]]=55
seri2

a    46
b    55
c    24
d    55
e    31
f    34
dtype: int32

In [33]:
pd.DataFrame(seri2)

0
a  46
b  55
c  24
d  55
e  31
f  34

In [34]:
pd.DataFrame(seri2,columns=["Sayılar"])

Sayılar
a       46
b       55
c       24
d       55
e       31
f       34

In [35]:
yeni_dizi=np.random.randint(25,size=12).reshape(4,3)
yeni_dizi

array([[11,  2,  4],
       [16, 21,  0],
       [10, 19, 22],
       [11, 11, 16]])

In [36]:
df=pd.DataFrame(yeni_dizi,columns=["col1","col2","col3"])
df

col1  col2  col3
0    11     2     4
1    16    21     0
2    10    19    22
3    11    11    16

In [37]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [38]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
df.columns=["1.Sütun","2.Sütun","3.Sütun"]
df

1.Sütun  2.Sütun  3.Sütun
0       11        2        4
1       16       21        0
2       10       19       22
3       11       11       16

In [40]:
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['1.Sütun', '2.Sütun', '3.Sütun'], dtype='object')]

In [41]:
df.ndim

2

In [42]:
df.shape

(4, 3)

In [43]:
df.values

array([[11,  2,  4],
       [16, 21,  0],
       [10, 19, 22],
       [11, 11, 16]])

In [44]:
a=np.random.randint(10,size=5)
b=np.random.randint(10,size=5)
c=np.random.randint(10,size=5)
print(a)
print(b)
print(c)

[6 7 4 2 8]
[2 4 6 2 0]
[0 4 0 5 8]


In [45]:
sozluk2={"Col1":a,"Col2":b,"Col3":c}
sozluk2

{'Col1': array([6, 7, 4, 2, 8]),
 'Col2': array([2, 4, 6, 2, 0]),
 'Col3': array([0, 4, 0, 5, 8])}

In [46]:
data=pd.DataFrame(sozluk2)
data

Col1  Col2  Col3
0     6     2     0
1     7     4     4
2     4     6     0
3     2     2     5
4     8     0     8

In [47]:
data[0:3]

Col1  Col2  Col3
0     6     2     0
1     7     4     4
2     4     6     0

In [48]:
data[1:-1]

Col1  Col2  Col3
1     7     4     4
2     4     6     0
3     2     2     5

In [49]:
data[::2]

Col1  Col2  Col3
0     6     2     0
2     4     6     0
4     8     0     8

In [50]:
data[1:4][["Col1","Col3"]]

Col1  Col3
1     7     4
2     4     0
3     2     5

In [51]:
data[0:3]["Col2"]

0    2
1    4
2    6
Name: Col2, dtype: int32

In [52]:
data[0:3][["Col2"]]

Col2
0     2
1     4
2     6

In [53]:
data[["Col1","Col3"]]

Col1  Col3
0     6     0
1     7     4
2     4     0
3     2     5
4     8     8

In [54]:
data[["Col2"]]

Col2
0     2
1     4
2     6
3     2
4     0

In [55]:
data

Col1  Col2  Col3
0     6     2     0
1     7     4     4
2     4     6     0
3     2     2     5
4     8     0     8

In [56]:
data.drop(1,axis=0)


Col1  Col2  Col3
0     6     2     0
2     4     6     0
3     2     2     5
4     8     0     8

In [57]:
data

Col1  Col2  Col3
0     6     2     0
1     7     4     4
2     4     6     0
3     2     2     5
4     8     0     8

In [60]:
data.drop(1,axis=0,inplace=True)

KeyError: '[1] not found in axis'

In [61]:
data

Col1  Col2  Col3
0     6     2     0
2     4     6     0
3     2     2     5
4     8     0     8

In [62]:
new_data=data.drop("Col2",axis=1)
new_data

Col1  Col3
0     6     0
2     4     0
3     2     5
4     8     8

In [63]:
data

Col1  Col2  Col3
0     6     2     0
2     4     6     0
3     2     2     5
4     8     0     8

In [64]:
data["Col4"]= data["Col1"]/data["Col2"]
data

Col1  Col2  Col3      Col4
0     6     2     0  3.000000
2     4     6     0  0.666667
3     2     2     5  1.000000
4     8     0     8       inf

In [65]:
seri2

a    46
b    55
c    24
d    55
e    31
f    34
dtype: int32

In [66]:
data2=pd.DataFrame(seri2)
data2

0
a  46
b  55
c  24
d  55
e  31
f  34

In [67]:
numbers=np.random.randint(40,size=(10,3))
numbers

array([[ 9, 20, 25],
       [12, 31, 21],
       [ 7, 32,  7],
       [ 1, 33,  2],
       [10, 21, 19],
       [ 5, 35, 39],
       [17,  9, 22],
       [29,  5, 31],
       [ 4, 17, 11],
       [18, 10, 10]])

In [69]:
df=pd.DataFrame(numbers,columns=["Col1","Col2","Col3"])
df

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39
6    17     9    22
7    29     5    31
8     4    17    11
9    18    10    10

In [70]:
df.loc[0,"Col3"]

25

In [71]:
df.iloc[0,2]

25

In [72]:
df.loc[6,"Col2"]

9

In [73]:
df.iloc[6,1]

9

In [74]:
df.loc[2:8,"Col2":"Col3"]

Col2  Col3
2    32     7
3    33     2
4    21    19
5    35    39
6     9    22
7     5    31
8    17    11

In [75]:
df.iloc[2:9,1:3]

Col2  Col3
2    32     7
3    33     2
4    21    19
5    35    39
6     9    22
7     5    31
8    17    11

In [76]:
df.loc[0:5]

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39

In [77]:
df.loc[2:7]

Col1  Col2  Col3
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39
6    17     9    22
7    29     5    31

In [78]:
df.loc[2:7,"Col2"]

2    32
3    33
4    21
5    35
6     9
7     5
Name: Col2, dtype: int32

In [79]:
df

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39
6    17     9    22
7    29     5    31
8     4    17    11
9    18    10    10

In [80]:
df["Col1"]>20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9    False
Name: Col1, dtype: bool

In [81]:
df[df["Col1"]>20]

Col1  Col2  Col3
7    29     5    31

In [82]:
df[df["Col1"]>20][["Col1"]]

Col1
7    29

In [83]:
df[df["Col3"]<30]

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
6    17     9    22
8     4    17    11
9    18    10    10

In [84]:
df[df["Col3"]<30][["Col3"]]

Col3
0    25
1    21
2     7
3     2
4    19
6    22
8    11
9    10

In [85]:
df[df["Col3"]<30][["Col2","Col3"]]

Col2  Col3
0    20    25
1    31    21
2    32     7
3    33     2
4    21    19
6     9    22
8    17    11
9    10    10

In [86]:
df[(df["Col2"]>20)&(df["Col3"]<30)]

Col1  Col2  Col3
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19

In [87]:
df

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39
6    17     9    22
7    29     5    31
8     4    17    11
9    18    10    10

In [88]:
df2=df+50
df2

Col1  Col2  Col3
0    59    70    75
1    62    81    71
2    57    82    57
3    51    83    52
4    60    71    69
5    55    85    89
6    67    59    72
7    79    55    81
8    54    67    61
9    68    60    60

In [89]:
pd.concat([df,df2])

Col1  Col2  Col3
0     9    20    25
1    12    31    21
2     7    32     7
3     1    33     2
4    10    21    19
5     5    35    39
6    17     9    22
7    29     5    31
8     4    17    11
9    18    10    10
0    59    70    75
1    62    81    71
2    57    82    57
3    51    83    52
4    60    71    69
5    55    85    89
6    67    59    72
7    79    55    81
8    54    67    61
9    68    60    60

In [91]:
pd.concat([df,df2],ignore_index=True)

Col1  Col2  Col3
0      9    20    25
1     12    31    21
2      7    32     7
3      1    33     2
4     10    21    19
5      5    35    39
6     17     9    22
7     29     5    31
8      4    17    11
9     18    10    10
10    59    70    75
11    62    81    71
12    57    82    57
13    51    83    52
14    60    71    69
15    55    85    89
16    67    59    72
17    79    55    81
18    54    67    61
19    68    60    60

In [92]:
df2.columns=["Col1","Col2","Col4"]
df2

Col1  Col2  Col4
0    59    70    75
1    62    81    71
2    57    82    57
3    51    83    52
4    60    71    69
5    55    85    89
6    67    59    72
7    79    55    81
8    54    67    61
9    68    60    60

In [93]:
pd.concat([df,df2])

Col1  Col2  Col3  Col4
0     9    20  25.0   NaN
1    12    31  21.0   NaN
2     7    32   7.0   NaN
3     1    33   2.0   NaN
4    10    21  19.0   NaN
5     5    35  39.0   NaN
6    17     9  22.0   NaN
7    29     5  31.0   NaN
8     4    17  11.0   NaN
9    18    10  10.0   NaN
0    59    70   NaN  75.0
1    62    81   NaN  71.0
2    57    82   NaN  57.0
3    51    83   NaN  52.0
4    60    71   NaN  69.0
5    55    85   NaN  89.0
6    67    59   NaN  72.0
7    79    55   NaN  81.0
8    54    67   NaN  61.0
9    68    60   NaN  60.0

In [94]:
pd.concat([df,df2],join="inner")

Col1  Col2
0     9    20
1    12    31
2     7    32
3     1    33
4    10    21
5     5    35
6    17     9
7    29     5
8     4    17
9    18    10
0    59    70
1    62    81
2    57    82
3    51    83
4    60    71
5    55    85
6    67    59
7    79    55
8    54    67
9    68    60

In [95]:
pd.concat([df,df2],axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0     9    20    25    59    70    75
1    12    31    21    62    81    71
2     7    32     7    57    82    57
3     1    33     2    51    83    52
4    10    21    19    60    71    69
5     5    35    39    55    85    89
6    17     9    22    67    59    72
7    29     5    31    79    55    81
8     4    17    11    54    67    61
9    18    10    10    68    60    60

In [96]:
import pandas as pd

In [97]:
data = pd.DataFrame({"Öğrenciler":["Ayşe","Mehmet","Fatma","Fatma","Mehmet","Ayşe","Ayşe","Fatma","Mehmet"],
                   "Dersler":["Matematik","Türkçe","Türkçe","Fen Bilgisi","Matematik","Fen Bilgisi","Türkçe","Matematik","Fen Bilgisi"],
                    "Puan":[80,75,92,78,64,84,73,94,90]})
data

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
1     Mehmet       Türkçe    75
2      Fatma       Türkçe    92
3      Fatma  Fen Bilgisi    78
4     Mehmet    Matematik    64
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [98]:
data[["Dersler"]][data["Öğrenciler"]=="Ayşe"]

Dersler
0    Matematik
5  Fen Bilgisi
6       Türkçe

In [99]:
data2 = pd.DataFrame({"Öğretmenler":["Selin","Furkan","Emine"],
                   "Dersler":["Matematik","Türkçe","Fen Bilgisi"]})
data2

Öğretmenler      Dersler
0       Selin    Matematik
1      Furkan       Türkçe
2       Emine  Fen Bilgisi

In [101]:
pd.merge(data,data2)

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [105]:
new_data=pd.merge(data,data2,on="Dersler")
new_data

Öğrenciler      Dersler  Puan Öğretmenler
0       Ayşe    Matematik    80       Selin
1     Mehmet    Matematik    64       Selin
2      Fatma    Matematik    94       Selin
3     Mehmet       Türkçe    75      Furkan
4      Fatma       Türkçe    92      Furkan
5       Ayşe       Türkçe    73      Furkan
6      Fatma  Fen Bilgisi    78       Emine
7       Ayşe  Fen Bilgisi    84       Emine
8     Mehmet  Fen Bilgisi    90       Emine

In [106]:
data["Öğrenciler"]

0      Ayşe
1    Mehmet
2     Fatma
3     Fatma
4    Mehmet
5      Ayşe
6      Ayşe
7     Fatma
8    Mehmet
Name: Öğrenciler, dtype: object

In [107]:
data[["Öğrenciler"]]

Öğrenciler
0       Ayşe
1     Mehmet
2      Fatma
3      Fatma
4     Mehmet
5       Ayşe
6       Ayşe
7      Fatma
8     Mehmet

In [108]:
data[data["Öğrenciler"]=="Ayşe"]

Öğrenciler      Dersler  Puan
0       Ayşe    Matematik    80
5       Ayşe  Fen Bilgisi    84
6       Ayşe       Türkçe    73

In [109]:
data[data["Öğrenciler"]=="Mehmet"]

Öğrenciler      Dersler  Puan
1     Mehmet       Türkçe    75
4     Mehmet    Matematik    64
8     Mehmet  Fen Bilgisi    90

In [114]:
data[data["Öğrenciler"]=="Mehmet"][["Dersler","Puan"]]

Dersler  Puan
1       Türkçe    75
4    Matematik    64
8  Fen Bilgisi    90

In [115]:
data[data["Dersler"]=="Matematik"]

Öğrenciler    Dersler  Puan
0       Ayşe  Matematik    80
4     Mehmet  Matematik    64
7      Fatma  Matematik    94

In [116]:
data[data["Dersler"]=="Fen Bilgisi"]

Öğrenciler      Dersler  Puan
3      Fatma  Fen Bilgisi    78
5       Ayşe  Fen Bilgisi    84
8     Mehmet  Fen Bilgisi    90

In [117]:
data[data["Dersler"]=="Fen Bilgisi"][["Öğrenciler","Puan"]]

Öğrenciler  Puan
3      Fatma    78
5       Ayşe    84
8     Mehmet    90

In [118]:
data[data["Puan"]>80]

Öğrenciler      Dersler  Puan
2      Fatma       Türkçe    92
5       Ayşe  Fen Bilgisi    84
7      Fatma    Matematik    94
8     Mehmet  Fen Bilgisi    90

In [119]:
data[(data["Dersler"]=="Matematik")&(data["Puan"]>80)]

Öğrenciler    Dersler  Puan
7      Fatma  Matematik    94

In [120]:
data[(data["Dersler"]=="Türkçe")&(data["Puan"]<85)]

Öğrenciler Dersler  Puan
1     Mehmet  Türkçe    75
6       Ayşe  Türkçe    73